import palette from "./colorPalette";
import DARK from "./palette/dark";
import LIGHT from "./palette/light";
import { alpha } from "../common/colorUtil";

const transparent = "transparent";

const lightColors = {
  brand_5: LIGHT.BLUE_5,
  brand_7: LIGHT.BLUE_7,
  brand_10: LIGHT.BLUE_10,
  brand_20: LIGHT.BLUE_20,
  brand_30: LIGHT.BLUE_30,
  brand_40: LIGHT.BLUE_40,
  brand_50: LIGHT.BLUE_50,
  brand_60: LIGHT.BLUE_60,
  brand_70: LIGHT.BLUE_70,
  brand_80: LIGHT.BLUE_80,
  brand_90: LIGHT.BLUE_90,
  brand_100: LIGHT.BLUE_100,
  brand_a10: LIGHT.BLUE_A10,
  primary_color: LIGHT.BLUE_50, // antd

  txt_static: LIGHT.INK_100,
  txt_default: LIGHT.INK_70,
  txt_hover: LIGHT.INK_100,
  txt_active: LIGHT.INK_100,
  txt_disabled: alpha(LIGHT.INK_70, 0.5),
  txt_label: LIGHT.INK_100,
  txt_point: LIGHT.BLUE_50,
  txt_link: LIGHT.BLUE_50,
  txt_desc: LIGHT.INK_50,
  heading_color: LIGHT.INK_100,

  border_default: LIGHT.INK_30,
  border_separate: LIGHT.INK_30,
  border_color_base: LIGHT.INK_30, // ant
  border_color_split: LIGHT.INK_30, // ant
  border_badge: LIGHT.INK_5,

  btn_primary_bg: LIGHT.BLUE_50,
  btn_primary_border: LIGHT.BLUE_50,
  btn_primary_color: LIGHT.INK_5,
  btn_primary_hover_bg: LIGHT.BLUE_40,
  btn_primary_hover_border: LIGHT.BLUE_40,
  btn_primary_hover_color: LIGHT.INK_5,
  btn_primary_active_bg: LIGHT.BLUE_60,
  btn_primary_active_border: LIGHT.BLUE_60,
  btn_primary_active_color: LIGHT.INK_5,
  btn_primary_disabled_bg: alpha(LIGHT.BLUE_50, 0.5),
  btn_primary_disabled_border: alpha(LIGHT.BLUE_50, 0.5),
  btn_primary_disabled_color: alpha(LIGHT.INK_5, 0.5),
  btn_default_bg: LIGHT.INK_5,
  btn_default_border: LIGHT.INK_30,
  btn_default_color: LIGHT.INK_70,
  btn_default_hover_bg: LIGHT.INK_10,
  btn_default_hover_border: LIGHT.INK_30,
  btn_default_hover_color: LIGHT.INK_70,
  btn_default_active_bg: LIGHT.INK_10,
  btn_default_active_border: LIGHT.INK_30,
  btn_default_active_color: LIGHT.INK_100,

  btn_disable_color: alpha(LIGHT.INK_100, 0.5),
  btn_disable_bg: alpha(LIGHT.INK_5, 0.5),
  btn_disable_border: alpha(LIGHT.INK_30, 0.5),

  btn_secondary_bg: transparent,
  btn_secondary_border: transparent,
  btn_secondary_color: LIGHT.INK_70,
  btn_secondary_hover_bg: LIGHT.BLUE_7,
  btn_secondary_hover_border: LIGHT.BLUE_7,
  btn_secondary_hover_color: LIGHT.BLUE_50,
  btn_secondary_active_bg: LIGHT.BLUE_A10,
  btn_secondary_active_border: LIGHT.BLUE_A10,
  btn_secondary_active_color: LIGHT.BLUE_80,

  btn_danger_bg: LIGHT.INK_5,
  btn_danger_border: LIGHT.YELLOW_50,
  btn_danger_color: LIGHT.YELLOW_90,
  btn_danger_hover_bg: LIGHT.YELLOW_5,
  btn_danger_hover_border: LIGHT.YELLOW_50,
  btn_danger_hover_color: LIGHT.INK_70,
  btn_danger_active_bg: LIGHT.YELLOW_5,
  btn_danger_active_border: LIGHT.YELLOW_50,
  btn_danger_active_color: LIGHT.INK_100,

  icn_btn: LIGHT.INK_70,
  icn_btn_hover: LIGHT.BLUE_50,
  icn_btn_active: LIGHT.BLUE_80,
  icn_btn_disabled: alpha(LIGHT.INK_100, 0.5),

  txt_btn: LIGHT.INK_70,
  txt_btn_hover: LIGHT.BLUE_50,
  txt_btn_active: LIGHT.BLUE_80,
  txt_btn_disabled: alpha(LIGHT.INK_100, 0.5),

  input_bg: LIGHT.INK_5,
  input_border_color: LIGHT.INK_30, // for antd
  input_addon_bg: LIGHT.INK_30,
  input_color: LIGHT.INK_70,
  input_hover_border_color: LIGHT.INK_30, // for antd
  input_bg_focus: LIGHT.INK_5,
  input_border_focus: LIGHT.INK_30,
  input_color_focus: LIGHT.INK_100,
  input_outline_focus: LIGHT.BLUE_A10,

  input_error_bg: LIGHT.INK_5,
  input_error_border: LIGHT.RED_50,
  input_error_color: LIGHT.RED_50,
  input_error_message: LIGHT.INK_100,
  input_error_outline: LIGHT.RED_10,
  input_disabled_bg: LIGHT.INK_20,
  input_disabled_border: LIGHT.INK_30,
  input_disabled_color: LIGHT.INK_70,

  checkbox_bg: LIGHT.INK_5,
  checkbox_border: LIGHT.INK_30,
  checkbox_txt: LIGHT.INK_100,
  checkbox_color: LIGHT.INK_5,
  checkbox_active_bg: LIGHT.INK_5,
  checkbox_active_border: LIGHT.INK_30,
  checkbox_active_txt: LIGHT.INK_100,
  checkbox_active_color: LIGHT.BLUE_50,
  checkbox_disabled_bg: alpha(LIGHT.INK_20, 0.5),
  checkbox_disabled_border: alpha(LIGHT.INK_30, 0.5),
  checkbox_disabled_txt: alpha(LIGHT.INK_100, 0.5),
  checkbox_disabled_color: alpha(LIGHT.INK_20, 0.5),

  checkbox_check_color: LIGHT.BLUE_50, // antd

  radio_bg: LIGHT.INK_5,
  radio_border: LIGHT.INK_30,
  radio_txt: LIGHT.INK_100,
  radio_color: LIGHT.INK_5,
  radio_active_bg: LIGHT.INK_5,
  radio_active_border: LIGHT.INK_30,
  radio_active_txt: LIGHT.INK_100,
  radio_active_color: LIGHT.BLUE_50,
  radio_disabled_bg: LIGHT.INK_20,
  radio_disabled_border: LIGHT.INK_30,
  radio_disabled_txt: LIGHT.INK_100,
  radio_disabled_color: LIGHT.INK_20,

  switch_bg: LIGHT.INK_30,
  switch_border: LIGHT.INK_30,
  switch_color: LIGHT.INK_5,
  switch_active_bg: LIGHT.BLUE_50,
  switch_active_border: LIGHT.BLUE_50,
  switch_active_color: LIGHT.INK_5,
  switch_disabled_bg: alpha(LIGHT.INK_30, 0.5),
  switch_disabled_border: alpha(LIGHT.INK_30, 0.5),
  switch_disabled_color: alpha(LIGHT.INK_100, 0.5),

  select_background: LIGHT.INK_5,
  select_dropdown_bg: LIGHT.INK_5,
  select_border: LIGHT.INK_30,
  select_txt: LIGHT.INK_100,
  select_icn: LIGHT.INK_70,
  select_hover_bg: LIGHT.BLUE_7,
  select_hover_border: LIGHT.INK_30,
  select_hover_txt: LIGHT.BLUE_50,
  select_hover_icn: LIGHT.INK_70,

  select_active_bg: LIGHT.BLUE_A10,
  select_active_border: LIGHT.INK_30,
  select_active_txt: LIGHT.BLUE_80,
  select_active_icn: LIGHT.BLUE_80,

  select_disabled_bg: alpha(LIGHT.INK_20, 0.5),
  select_disabled_border: alpha(LIGHT.INK_30, 0.5),
  select_disabled_txt: alpha(LIGHT.INK_100, 0.5),
  select_disabled_icn: alpha(LIGHT.INK_70, 0.5),

  cascader_bg: LIGHT.INK_5,

  list_bg: LIGHT.INK_5,
  list_border: LIGHT.INK_30,
  list_color: LIGHT.INK_70,
  list_hover_bg: LIGHT.INK_10,
  list_hover_border: LIGHT.INK_30,
  list_hover_color: LIGHT.INK_70,
  // end defined of notion

  // antd styles
  white_color: LIGHT.INK_5,
  error_color: LIGHT.RED_50,
  success_color: LIGHT.GREEN_50,
  info_color: LIGHT.BLUE_50,
  highlight_color: LIGHT.RED_50,
  disabled_color: alpha(LIGHT.INK_70, 0.5),
  warning_color: LIGHT.YELLOW_50,

  text_color: LIGHT.INK_100,
  text_color_hover: LIGHT.INK_100,
  text_color_active: LIGHT.INK_100,
  text_color_secondary: LIGHT.INK_100,
  text_color_secondary_hover: LIGHT.INK_100,
  text_color_secondary_active: LIGHT.INK_100,

  body_background: LIGHT.INK_7,
  label_color: LIGHT.INK_100,
  title_color: LIGHT.INK_100,
  component_background: LIGHT.INK_5,
  popover_bg: LIGHT.INK_5,

  // querypie styles
  item_hover_bg: LIGHT.BLUE_7,
  item_hover_color: LIGHT.BLUE_50,
  item_active_bg: LIGHT.BLUE_A10,
  item_active_color: LIGHT.BLUE_80,
  tree_item_hover_bg: LIGHT.BLUE_7,
  tree_item_active_bg: LIGHT.BLUE_A10,

  datagrid_border: `1px solid ${LIGHT.INK_30}`,
  datagrid_header: LIGHT.INK_5,
  datagrid_body: LIGHT.INK_5,
  datagrid_status: LIGHT.INK_10,
  datagrid_selected: LIGHT.BLUE_7,
  datagrid_added: LIGHT.BLUE_5,
  datagrid_updated: LIGHT.BLUE_A10,
  datagrid_deleted: LIGHT.INK_20,
  datagrid_deleted_text: alpha(LIGHT.INK_100, 0.5),
  datagrid_error: LIGHT.RED_10,
  datagrid_column_sorter_bg: LIGHT.INK_30,
  datagrid_body_tr_bg: LIGHT.INK_10,
  datagrid_body_tr_even_bg: LIGHT.INK_5,
  datagrid_editinput_bg: LIGHT.INK_5,

  tree_directory_selected_color: LIGHT.INK_100,
  tree_directory_selected_bg: LIGHT.INK_10,
  tree_directory_badge_bg: LIGHT.BLUE_5,
  tree_directory_badge_color: LIGHT.BLUE_50,

  table_bg: LIGHT.INK_5,
  table_header_bg: LIGHT.INK_5,
  table_header_border_color: LIGHT.INK_30,
  table_body_tr_bg: LIGHT.INK_10,
  table_body_tr_even_bg: LIGHT.INK_5,

  box_40_bg: LIGHT.INK_10,
  box_50_bg: LIGHT.INK_10, // default
  box_50_border: LIGHT.INK_80,
  box_60_bg: LIGHT.INK_5,

  notification_bg: LIGHT.INK_5,
  dialog_bg: LIGHT.INK_5,
  tooltip_color: LIGHT.INK_100,
  tooltip_bg: LIGHT.INK_5,
  tooltip_border_color: LIGHT.INK_30,
  modal_header_bg: LIGHT.INK_5,
  modal_body_bg: LIGHT.INK_5,
  modal_body_2_bg: LIGHT.INK_10,
  popover_background: LIGHT.INK_5,
  popover_color: LIGHT.INK_70,
  popover_shadow: `0px 4px 8px rgba(15, 38, 53, 0.24)`,
  message_notice_content_bg: LIGHT.BLUE_100,
  message_border: `0 none`,
  message_color: LIGHT.INK_5,
  window_header_bg: LIGHT.INK_5,
  ms_window_border: LIGHT.BLUE_50,
  scroll_track_color: LIGHT.INK_5,
  scroll_thumb_color: LIGHT.INK_50,
  l_sidebar_bg: LIGHT.BLUE_80,
  statusbar_bg: LIGHT.BLUE_7,
  statusbar_color: LIGHT.BLUE_70,

  setting_tab_bg: LIGHT.INK_10,
  setting_tab_active_bg: LIGHT.INK_5,
  page_main_recent_connection_list_bg: LIGHT.INK_10,
  page_main_recent_connection_list_border_color: LIGHT.INK_30,
  page_connection_bg: LIGHT.INK_5,
  page_connection_toolbar_bg: LIGHT.INK_10,
  page_connection_buttonbar_bg: LIGHT.INK_10,
  page_connection_formgroup_bg: LIGHT.INK_10,

  workspace_bg: LIGHT.BLUE_60,
  workspace_txt_color: LIGHT.BLUE_5,
  workspace_sider_bg: LIGHT.BLUE_90,
  workspace_popover_list_bg: LIGHT.INK_5,
  workspace_popover_list_hover_bg: LIGHT.BLUE_7,
  workspace_popover_list_active_bg: LIGHT.INK_5,
  workspace_popover_menu_hover_bg: LIGHT.BLUE_7,
  workspace_list_bg: LIGHT.INK_10,
  workspace_list_hover_bg: LIGHT.BLUE_7,
  workspace_list_active_bg: LIGHT.BLUE_A10,

  object_browser_bg: LIGHT.INK_10,
  object_browser_formitem_bg: LIGHT.INK_5,
  panel_toolbar_bg: LIGHT.INK_5,
  panel_toolbar_btn_bg: LIGHT.INK_5,
  panel_toolbar_btn_border: `1px solid ${LIGHT.INK_30}`,
  panel_toolbar_btn_active_bg: LIGHT.BLUE_A10,
  panel_toolbar_btn_active_color: LIGHT.BLUE_80,
  panel_toolbar_btn_active_border: `1px solid ${LIGHT.BLUE_80}`,
  panel_toolbar_switch_on_color: LIGHT.GREEN_90,
  panel_toolbar_switch_on_bg: LIGHT.GREEN_10,
  panel_toolbar_switch_off_color: LIGHT.RED_90,
  panel_toolbar_switch_off_bg: LIGHT.RED_10,

  aside_bar_bg: LIGHT.INK_10,
  aside_bar_active_bg: LIGHT.INK_5,
  aside_panel_bg: LIGHT.INK_5,
  aside_panel_toolbar_bg: LIGHT.INK_10,
  aside_panel_tab_bg: LIGHT.INK_10,
  aside_panel_tab_active_bg: LIGHT.INK_5,
  aside_panel_buttonbar_bg: LIGHT.INK_10,
  connection_switch_popover_bg: LIGHT.INK_5,
  connection_switch_popover_active_bg: LIGHT.INK_10,
  connection_switch_shadow: `0px 2px 4px rgba(15, 38, 53, 0.24)`,
  sqleditor_tab_bg: LIGHT.INK_10,
  sqleditor_tab_hover_bg: LIGHT.INK_5,
  sqleditor_tab_active_bg: LIGHT.INK_5,
  sqleditor_tab_border_width: "0",
  sqleditor_editor_bg: LIGHT.INK_5,
  sqleditor_result_toolbar_bg: LIGHT.INK_10,
  sqleditor_result_toolbar_border_width: "0",
  sqleditor_result_bg: LIGHT.INK_5,
  sqleditor_result_tab_bg: LIGHT.INK_10,
  sqleditor_result_tab_hover_bg: LIGHT.INK_5,
  sqleditor_result_tab_active_bg: LIGHT.INK_5,
  sqleditor_result_box_bg: LIGHT.INK_5,
  notebook_tab_bg: LIGHT.INK_5,
  notebook_tab_hover_bg: LIGHT.INK_5,
  notebook_tab_active_bg: LIGHT.INK_5,
  modal_tab_bg: LIGHT.INK_10,
  modal_tab_content_bg: LIGHT.INK_5,
  modal_tab_content_component_bg: LIGHT.INK_5,
  modal_tab_content_component_item_bg: LIGHT.INK_10,
  modal_tab_content_component_tool_bg: LIGHT.INK_10,
  modal_tab_content_editor_bg: LIGHT.INK_5,

  sql_history_code_bg: LIGHT.INK_10,
  is_connected_border_color: LIGHT.INK_5,
  spinner_bg: transparent,
  monaco_editor_widget_bg: LIGHT.INK_5,
};

// dark component colors
const darkColors: typeof lightColors = {
  brand_5: LIGHT.BLUE_5,
  brand_7: LIGHT.BLUE_7,
  brand_10: DARK.BLUE_10,
  brand_20: DARK.BLUE_20,
  brand_30: DARK.BLUE_30,
  brand_40: DARK.BLUE_40,
  brand_50: DARK.BLUE_50,
  brand_60: DARK.BLUE_60,
  brand_70: DARK.BLUE_70,
  brand_80: DARK.BLUE_80,
  brand_90: DARK.BLUE_90,
  brand_100: DARK.BLUE_100,
  brand_a10: LIGHT.BLUE_A10,
  primary_color: DARK.BLUE_50, // antd

  txt_static: DARK.INK_1,
  txt_default: DARK.INK_5,
  txt_hover: DARK.INK_1,
  txt_active: DARK.INK_1,
  txt_disabled: alpha(DARK.INK_5, 0.5),
  txt_label: DARK.BLUE_30,
  txt_point: DARK.BLUE_60,
  txt_link: DARK.BLUE_60,
  txt_desc: LIGHT.INK_5,
  heading_color: DARK.INK_1,

  border_default: DARK.INK_A10,
  border_separate: DARK.INK_20,
  border_color_base: DARK.INK_A10,
  border_color_split: DARK.INK_20,
  border_badge: DARK.INK_40,

  btn_primary_bg: DARK.BLUE_60,
  btn_primary_border: DARK.BLUE_50,
  btn_primary_color: DARK.INK_1,
  btn_primary_hover_bg: DARK.BLUE_50,
  btn_primary_hover_border: DARK.BLUE_50,
  btn_primary_hover_color: DARK.INK_1,
  btn_primary_active_bg: DARK.BLUE_70,
  btn_primary_active_border: DARK.BLUE_70,
  btn_primary_active_color: DARK.INK_1,
  btn_primary_disabled_bg: alpha(DARK.BLUE_60, 0.5),
  btn_primary_disabled_border: alpha(DARK.BLUE_60, 0.5),
  btn_primary_disabled_color: alpha(DARK.INK_1, 0.5),
  btn_default_bg: DARK.INK_10,
  btn_default_border: DARK.INK_A10,
  btn_default_color: DARK.INK_1,
  btn_default_hover_bg: DARK.INK_7,
  btn_default_hover_border: DARK.INK_7,
  btn_default_hover_color: DARK.INK_1,
  btn_default_active_bg: DARK.INK_20,
  btn_default_active_border: DARK.INK_20,
  btn_default_active_color: DARK.INK_1,

  btn_disable_color: alpha(DARK.INK_1, 0.5),
  btn_disable_bg: alpha(DARK.INK_10, 0.5),
  btn_disable_border: alpha(DARK.INK_10, 0.5),

  btn_secondary_bg: transparent,
  btn_secondary_border: transparent,
  btn_secondary_color: DARK.INK_1,
  btn_secondary_hover_bg: DARK.INK_10,
  btn_secondary_hover_border: DARK.INK_10,
  btn_secondary_hover_color: DARK.INK_1,
  btn_secondary_active_bg: DARK.INK_10,
  btn_secondary_active_border: DARK.INK_1,
  btn_secondary_active_color: DARK.INK_100,

  btn_danger_bg: DARK.ORANGE_50,
  btn_danger_border: DARK.ORANGE_50,
  btn_danger_color: DARK.INK_1,
  btn_danger_hover_bg: DARK.ORANGE_10,
  btn_danger_hover_border: DARK.ORANGE_10,
  btn_danger_hover_color: DARK.INK_1,
  btn_danger_active_bg: DARK.ORANGE_90,
  btn_danger_active_border: DARK.ORANGE_90,
  btn_danger_active_color: DARK.INK_1,

  icn_btn: DARK.INK_5,
  icn_btn_hover: DARK.INK_1,
  icn_btn_active: DARK.INK_1,
  icn_btn_disabled: alpha(DARK.INK_5, 0.5),

  txt_btn: DARK.INK_5,
  txt_btn_hover: DARK.INK_1,
  txt_btn_active: DARK.INK_1,
  txt_btn_disabled: alpha(DARK.INK_5, 0.5),

  input_bg: DARK.INK_80,
  input_border_color: DARK.INK_A10, // ant
  input_addon_bg: DARK.INK_A10,
  input_color: DARK.INK_5,
  input_hover_border_color: LIGHT.BLUE_60, // antd
  input_bg_focus: DARK.INK_80,
  input_border_focus: DARK.BLUE_60,
  input_color_focus: DARK.INK_1,
  input_outline_focus: "none",
  input_error_bg: DARK.INK_80,
  input_error_border: "none",
  input_error_color: DARK.INK_1,
  input_error_message: DARK.RED_50,
  input_error_outline: DARK.RED_50,
  input_disabled_bg: alpha(DARK.INK_80, 0.5),
  input_disabled_border: alpha(DARK.INK_A10, 0.5),
  input_disabled_color: alpha(DARK.INK_5, 0.5),

  checkbox_bg: DARK.INK_80,
  checkbox_border: DARK.INK_A10,
  checkbox_txt: DARK.INK_5,
  checkbox_color: DARK.INK_80,
  checkbox_active_bg: DARK.INK_80,
  checkbox_active_border: DARK.INK_A10,
  checkbox_active_txt: DARK.INK_5,
  checkbox_active_color: DARK.BLUE_60,
  checkbox_disabled_bg: alpha(DARK.INK_80, 0.5),
  checkbox_disabled_border: alpha(DARK.INK_A10, 0.5),
  checkbox_disabled_txt: alpha(DARK.INK_5, 0.5),
  checkbox_disabled_color: alpha(DARK.INK_80, 0.5),

  checkbox_check_color: DARK.BLUE_60, // antd

  radio_bg: DARK.INK_80,
  radio_border: DARK.INK_A10,
  radio_txt: DARK.INK_5,
  radio_color: DARK.INK_80,
  radio_active_bg: DARK.INK_80,
  radio_active_border: DARK.INK_A10,
  radio_active_txt: DARK.INK_5,
  radio_active_color: DARK.BLUE_60,
  radio_disabled_bg: alpha(DARK.INK_80, 0.5),
  radio_disabled_border: alpha(DARK.INK_A10, 0.5),
  radio_disabled_txt: alpha(DARK.INK_5, 0.5),
  radio_disabled_color: alpha(DARK.INK_80, 0.5),

  switch_bg: DARK.INK_30,
  switch_border: DARK.INK_30,
  switch_color: DARK.INK_1,
  switch_active_bg: DARK.BLUE_50,
  switch_active_border: DARK.BLUE_50,
  switch_active_color: DARK.INK_1,
  switch_disabled_bg: alpha(DARK.INK_30, 0.5),
  switch_disabled_border: alpha(DARK.INK_30, 0.5),
  switch_disabled_color: alpha(DARK.INK_100, 0.5),

  select_background: DARK.INK_80,
  select_dropdown_bg: DARK.INK_40,
  select_border: DARK.INK_A10,
  select_txt: DARK.INK_5,
  select_icn: DARK.INK_5,
  select_hover_bg: alpha(DARK.BLUE_80, 0.4),
  select_hover_border: DARK.BLUE_60,
  select_hover_txt: DARK.INK_5,
  select_hover_icn: DARK.INK_5,

  select_active_bg: DARK.BLUE_80,
  select_active_border: DARK.BLUE_60,
  select_active_txt: DARK.INK_5,
  select_active_icn: DARK.INK_5,

  select_disabled_bg: alpha(DARK.INK_80, 0.5),
  select_disabled_border: alpha(DARK.INK_A10, 0.5),
  select_disabled_txt: alpha(DARK.INK_5, 0.5),
  select_disabled_icn: alpha(DARK.INK_5, 0.5),

  cascader_bg: DARK.INK_80,

  list_bg: DARK.INK_40,
  list_border: DARK.INK_A10,
  list_color: DARK.INK_5,
  list_hover_bg: alpha(DARK.BLUE_80, 0.4),
  list_hover_border: DARK.INK_A10,
  list_hover_color: DARK.INK_5,
  // end defined of notion

  // antd styles ~
  white_color: DARK.INK_1,
  error_color: DARK.RED_50,
  success_color: DARK.GREEN_50,
  info_color: DARK.SKYBLUE_50,
  highlight_color: DARK.RED_50,
  disabled_color: DARK.INK_5,
  warning_color: DARK.ORANGE_50,

  text_color: DARK.INK_1,
  text_color_hover: DARK.INK_1,
  text_color_active: DARK.INK_1,
  text_color_secondary: DARK.INK_5,
  text_color_secondary_hover: DARK.INK_1,
  text_color_secondary_active: DARK.INK_1,

  body_background: DARK.INK_80,
  label_color: DARK.BLUE_30,
  title_color: DARK.INK_1,
  component_background: DARK.INK_50,
  popover_bg: DARK.INK_40,

  // querypie styles
  item_hover_bg: alpha(DARK.BLUE_80, 0.4),
  item_hover_color: DARK.INK_1,
  item_active_bg: DARK.BLUE_80,
  item_active_color: DARK.INK_1,
  tree_item_hover_bg: alpha(DARK.BLUE_80, 0.4),
  tree_item_active_bg: DARK.BLUE_80,

  datagrid_border: `1px solid ${DARK.INK_A10}`,
  datagrid_header: DARK.INK_60,
  datagrid_body: DARK.INK_70,
  datagrid_status: DARK.INK_60,
  datagrid_selected: DARK.INK_90,
  datagrid_added: DARK.INK_90,
  datagrid_updated: DARK.BLUE_80,
  datagrid_deleted: DARK.INK_50,
  datagrid_deleted_text: alpha(DARK.INK_5, 0.5),
  datagrid_error: DARK.RED_10,
  datagrid_column_sorter_bg: DARK.INK_60,
  datagrid_body_tr_bg: DARK.INK_70,
  datagrid_body_tr_even_bg: DARK.INK_80,
  datagrid_editinput_bg: DARK.INK_80,

  tree_directory_selected_color: DARK.INK_1,
  tree_directory_selected_bg: DARK.INK_10,
  tree_directory_badge_bg: DARK.BLUE_70,
  tree_directory_badge_color: DARK.INK_1,

  table_bg: DARK.INK_50,
  table_header_bg: DARK.INK_50,
  table_header_border_color: DARK.INK_50,
  table_body_tr_bg: DARK.INK_70,
  table_body_tr_even_bg: DARK.INK_80,

  box_40_bg: DARK.INK_30,
  box_50_bg: DARK.INK_50, // default
  box_50_border: DARK.INK_50,
  box_60_bg: DARK.INK_80,

  notification_bg: DARK.INK_50,
  dialog_bg: DARK.INK_50,
  tooltip_color: DARK.INK_5,
  tooltip_bg: DARK.INK_100,
  tooltip_border_color: DARK.INK_100,
  modal_header_bg: DARK.INK_60,
  modal_body_bg: DARK.INK_50,
  modal_body_2_bg: DARK.INK_50,
  popover_background: DARK.INK_40,
  popover_color: DARK.INK_5,
  popover_shadow: `0px 9px 10px rgba(15, 38, 53, 0.3)`,
  message_notice_content_bg: DARK.INK_40,
  message_border: `1px solid ${DARK.INK_A10}`,
  message_color: DARK.INK_5,
  window_header_bg: DARK.INK_60,
  ms_window_border: DARK.BLUE_50,
  scroll_track_color: DARK.INK_60,
  scroll_thumb_color: DARK.INK_10,
  l_sidebar_bg: DARK.INK_30,
  statusbar_bg: DARK.INK_100,
  statusbar_color: DARK.INK_5,

  setting_tab_bg: DARK.INK_30,
  setting_tab_active_bg: DARK.INK_50,
  page_main_recent_connection_list_bg: DARK.INK_50,
  page_main_recent_connection_list_border_color: DARK.INK_50,
  page_connection_bg: DARK.INK_50,
  page_connection_toolbar_bg: DARK.INK_50,
  page_connection_buttonbar_bg: DARK.INK_60,
  page_connection_formgroup_bg: DARK.INK_30,

  workspace_bg: DARK.BLUE_60,
  workspace_txt_color: DARK.BLUE_5,
  workspace_sider_bg: DARK.INK_70,
  workspace_popover_list_bg: DARK.INK_30,
  workspace_popover_list_hover_bg: alpha(DARK.BLUE_80, 0.4),
  workspace_popover_list_active_bg: DARK.INK_30,
  workspace_popover_menu_hover_bg: DARK.INK_20,
  workspace_list_bg: DARK.INK_30,
  workspace_list_hover_bg: alpha(DARK.BLUE_80, 0.4),
  workspace_list_active_bg: DARK.BLUE_80,

  object_browser_bg: DARK.INK_50,
  object_browser_formitem_bg: DARK.INK_90,
  panel_toolbar_bg: DARK.INK_50,
  panel_toolbar_btn_bg: DARK.INK_10,
  panel_toolbar_btn_border: `0 none`,
  panel_toolbar_btn_active_bg: DARK.INK_80,
  panel_toolbar_btn_active_color: DARK.INK_1,
  panel_toolbar_btn_active_border: `0 none`,
  panel_toolbar_switch_on_color: DARK.GREEN_50,
  panel_toolbar_switch_on_bg: DARK.INK_80,
  panel_toolbar_switch_off_color: DARK.RED_90,
  panel_toolbar_switch_off_bg: DARK.INK_80,
  aside_bar_bg: DARK.INK_30,
  aside_bar_active_bg: DARK.INK_60,
  aside_panel_bg: DARK.INK_90,
  aside_panel_toolbar_bg: DARK.INK_60,
  aside_panel_tab_bg: DARK.INK_60,
  aside_panel_tab_active_bg: DARK.INK_90,
  aside_panel_buttonbar_bg: DARK.INK_60,
  connection_switch_popover_bg: DARK.INK_40,
  connection_switch_popover_active_bg: DARK.INK_70,
  connection_switch_shadow: `0px 9px 10px rgba(15, 38, 53, 0.3)`,
  sqleditor_tab_bg: DARK.INK_60,
  sqleditor_tab_hover_bg: DARK.INK_70,
  sqleditor_tab_active_bg: DARK.INK_90,
  sqleditor_tab_border_width: "1px",
  sqleditor_editor_bg: DARK.INK_90,
  sqleditor_result_toolbar_bg: DARK.INK_60,
  sqleditor_result_toolbar_border_width: "1px",
  sqleditor_result_bg: DARK.INK_90,
  sqleditor_result_tab_bg: DARK.INK_60,
  sqleditor_result_tab_hover_bg: DARK.INK_70,
  sqleditor_result_tab_active_bg: DARK.INK_90,
  sqleditor_result_box_bg: DARK.INK_10,
  notebook_tab_bg: DARK.INK_60,
  notebook_tab_hover_bg: DARK.INK_70,
  notebook_tab_active_bg: DARK.INK_90,

  modal_tab_bg: DARK.INK_60,
  modal_tab_content_bg: DARK.INK_30,
  modal_tab_content_component_bg: DARK.INK_80,
  modal_tab_content_component_item_bg: DARK.INK_30,
  modal_tab_content_component_tool_bg: DARK.INK_60,
  modal_tab_content_editor_bg: DARK.INK_90,

  sql_history_code_bg: DARK.INK_60,
  is_connected_border_color: DARK.INK_80,
  spinner_bg: `rgba(0, 0, 0, 0.1)`,
  monaco_editor_widget_bg: DARK.INK_40,
};

const commons = {
  minPanelWidth: 300,
  lSiderWidth: 66,
  rSiderWidth: 23,
  heading_font_family: "sans-serif",

  border_radius_base: "2px",

  modal_header_height: "40px",

  // ~~
  screen_xs: "380px",
  screen_sm: "476px",
  screen_md: "768px",
  screen_lg: "992px",
  screen_xl: "1200px",
  screen_xxl: "1600px",

  ui_helper_zindex: 100,

  checkbox_size: "16px",

  btn_border_radius_base: "3px",
  btn_border_radius_sm: "3px",
  btn_height_base: "28px",
  btn_height_lg: "36px",
  btn_height_sm: "22px",

  tree_title_height: "28px",
  tree_child_padding: "10px",
};

const light = {
  ...lightColors,
  ...commons,
};

const dark = {
  ...darkColors,
  ...commons,
};

export const themePalette = {
  light,
  dark,
};

export default dark;
